In [ ]:
import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
import numpy as np 
from collections import Counter
from skimage.color import rgb2lab, deltaE_cie76
from sklearn.cluster import KMeans
from matplotlib import colors
from  matplotlib import pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import joblib
import tensorflow as tf
from tensorflow import keras
from skimage.io import imread
from skimage.transform import resize
from sklearn import svm
import imutils
from imutils import paths

import cv2
import os

In [ ]:
from matplotlib.colors import to_hex,rgb2hex
def get_images(eye_dataset):
  image_array =[]
  ordered_colors_array =[]
  hex_colors_array= []
  rgb_colors_array=[]
  class_name=[]
  flattened_array=[]

  IMG_HEIGHT = 32
  IMG_WIDTH =32
  colors =[]
  for folder in os.listdir(eye_dataset):
    for file in os.listdir(os.path.join(eye_dataset,folder)):
      
      try:
        image_path = os.path.join(eye_dataset,folder,file)
        image= cv2.imread(image_path,cv2.IMREAD_COLOR)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        #hex_color = colors.to_hex(image.shape[2])
        image=np.array(image)
        #print(image.shape[2])

        try:

          ht =image.shape[0]
          wd =image.shape[1]
          cc =image.shape[2] 

          top_pad = np.floor((ht - image.shape[0]) / 2).astype(np.uint16)
          bottom_pad = np.ceil((ht - image.shape[0]) / 2).astype(np.uint16)
          right_pad = np.ceil((wd - image.shape[1]) / 2).astype(np.uint16)
          left_pad = np.floor((wd - image.shape[1]) / 2).astype(np.uint16)
          image = np.copy(np.pad(image, ((top_pad, bottom_pad), (left_pad, right_pad), (0, 0)), mode='constant', constant_values=0))

          ht =0
          wd =0
          cc =0

        except Exception as e:
            print(str(e))

        resized_image = cv2.resize(image, (IMG_HEIGHT,IMG_WIDTH), interpolation = cv2.INTER_AREA)
        reshaped_image = image.reshape(image.shape[0]*image.shape[1], 3)
        

        kmeans = KMeans(n_clusters = 2)
        labels = kmeans.fit_predict(reshaped_image)

        counts = Counter(labels)

        center_colors = kmeans.cluster_centers_
        #print(center_colors)

        # We get ordered colors by iterating through the keys
        ordered_colors = [np.round(center_colors[i]).astype(int) for i in counts.keys()]
       # round_to_whole = [round(num) for num in a_list]
        #hex_colors = [rgb2hex(ordered_colors[i]) for i in counts.keys()]
        rgb_colors = [ordered_colors[i] for i in counts.keys()]
        flattened_colors= [(ordered_colors[i]).flatten() for i in counts.keys()]


          #return rgb_colors

        
        # flat_image= reshaped_image.flatten()
          #print(image.shape)  
        
          #image = image.astype('float32')
        #print(flat_image)

      
      except Exception as e:
        print(str(e))

      
      ordered_colors_array.append(ordered_colors)
      #hex_colors_array.append(hex_colors)
      flattened_array.append(flattened_colors)
      rgb_colors_array.append(rgb_colors)
      class_name.append(folder)

  return ordered_colors_array, rgb_colors_array,class_name,flattened_array


In [ ]:
def reshape_image(image_array):
  reshaped_images =[]
  for image in image_array:
    reshaped_image = image.reshape(image.shape[0]*image.shape[1], 3)
    reshaped_images.append(reshaped_image)

  return reshaped_images

In [ ]:
def predict_color(reshaped_images):
  for image in reshaped_images:
    kmeans = KMeans(n_clusters = 2)
    labels = kmeans.fit_predict(image)
    

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
ordered_colors_array, rgb_colors_array, class_name, flattened_array = get_images(r'/content/drive/MyDrive/Docsun Health/Eyes Dataset/Edited Dataset/')

In [ ]:
ordered_np_array.shape

(557, 2, 3)

In [ ]:
hex_colors = [RGB2HEX(ordered_colors[i]) for i in counts.keys()]

In [ ]:
rgb_colors_array

[[array([114,  97,  33]), array([254, 254, 250])],
 [array([108,  95,  37]), array([254, 254, 252])],
 [array([176, 138,  66]), array([254, 252, 248])],
 [array([115, 111,  79]), array([254, 254, 254])],
 [array([52, 29, 13]), array([234, 196, 105])],
 [array([253, 252, 246]), array([143, 111,  56])],
 [array([97, 85, 35]), array([252, 250, 244])],
 [array([172, 137,  61]), array([254, 254, 251])],
 [array([136, 112,   8]), array([255, 255, 254])],
 [array([235, 232, 214]), array([109,  82,  58])],
 [array([114,  85,  20]), array([254, 254, 253])],
 [array([119,  70,  28]), array([252, 251, 249])],
 [array([98, 66, 33]), array([250, 229, 194])],
 [array([255, 255, 254]), array([207, 148,  83])],
 [array([244, 232, 214]), array([102,  78,  43])],
 [array([142, 122,   5]), array([255, 254, 254])],
 [array([82, 67, 83]), array([236, 226, 206])],
 [array([107,  95,  36]), array([255, 254, 254])],
 [array([251, 250, 244]), array([144, 123,  77])],
 [array([255, 254, 254]), array([122,  91, 

In [ ]:
flat_array =[]
for i in flattened_np_array:
  flat =i.flatten()
  flat_array.append(flat)


flat_array

[array([114,  97,  33, 254, 254, 250]),
 array([108,  95,  37, 254, 254, 252]),
 array([176, 138,  66, 254, 252, 248]),
 array([254, 254, 254, 115, 111,  79]),
 array([ 52,  29,  13, 234, 196, 105]),
 array([143, 111,  56, 253, 252, 246]),
 array([252, 250, 244,  97,  85,  35]),
 array([172, 137,  61, 254, 254, 251]),
 array([136, 112,   8, 255, 255, 254]),
 array([235, 232, 213, 108,  81,  57]),
 array([114,  85,  20, 254, 254, 253]),
 array([119,  70,  28, 252, 251, 249]),
 array([250, 229, 194,  98,  65,  33]),
 array([255, 255, 254, 207, 148,  83]),
 array([103,  79,  43, 244, 233, 216]),
 array([255, 254, 254, 142, 122,   5]),
 array([236, 226, 206,  82,  67,  83]),
 array([255, 254, 254, 107,  95,  36]),
 array([144, 123,  77, 251, 250, 244]),
 array([255, 254, 254, 122,  91,  43]),
 array([161, 120,  80, 254, 254, 253]),
 array([128, 122,  87, 255, 254, 252]),
 array([215, 216, 169,  82,  75,  41]),
 array([105,  81,  54, 212, 201, 175]),
 array([124,  82,  44, 254, 254, 253]),


In [ ]:
flat_np_array = np.array(flat_array)

In [ ]:
flat_np_array.shape

(557, 6)

In [ ]:
class_names =np.array(class_name)
class_names.shape

(557,)

In [ ]:
class_names

array(['yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow eyes',
       'yellow eyes', 'yellow eyes', 'yellow eyes', 'yellow ey

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
target = le.fit_transform(class_names)
target

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
color_dataset=scaler.fit_transform(flat_np_array)

In [ ]:
target.shape

(557,)

In [ ]:
color_dataset

array([[-0.97032252, -0.82816182, -1.43577006,  1.11381373,  1.18439941,
         1.15642571],
       [-1.05486116, -0.85233887, -1.39023224,  1.11381373,  1.18439941,
         1.17947643],
       [-0.09675653, -0.33253218, -1.06008299,  1.11381373,  1.15967912,
         1.133375  ],
       ...,
       [ 0.95997652,  1.02138294,  1.03465703, -0.80281331, -0.83030451,
        -0.73373275],
       [ 0.88952765,  0.77961238,  0.86389018, -0.95448883, -1.01570671,
        -0.89508774],
       [-1.54800325, -1.15455207, -0.95762289,  0.75530795,  0.8383153 ,
         0.8682918 ]])

In [ ]:
color_dataset.shape

(557, 6)

In [ ]:
X = color_dataset
y = target


In [ ]:
from sklearn.utils import shuffle
X_shuffled,y_shuffled = shuffle(X, y, random_state=32)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_shuffled, y_shuffled, test_size=0.30, random_state=30)

In [ ]:
svm_model = svm.SVC(kernel='rbf', probability=True, random_state=42, gamma='auto', max_iter = 200)

In [ ]:
svm_model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=200, probability=True, random_state=42, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
svm_predicted_y = svm_model.predict(X_test)

In [ ]:
svm_predicted_y

array([1, 2, 2, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 2, 1,
       1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 1, 2, 1, 2, 0, 0, 1, 0, 2, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       2, 1, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1])

In [ ]:
from sklearn import metrics
meanAbsError = metrics.mean_absolute_error(np.array(y_test), svm_predicted_y)
meanSqrdError = metrics.mean_squared_error(np.array(y_test), svm_predicted_y)
rootMeanSqrdError = np.sqrt(meanSqrdError)

In [ ]:
print(" SVM Classification Report: \n{}\n".format(metrics.classification_report(y_test, svm_predicted_y, target_names=['0','1','2'], zero_division = 1)))

 SVM Classification Report: 
              precision    recall  f1-score   support

           0       0.70      0.71      0.71        56
           1       0.70      0.96      0.81        70
           2       1.00      0.36      0.53        42

    accuracy                           0.73       168
   macro avg       0.80      0.68      0.68       168
weighted avg       0.77      0.73      0.70       168




In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy on SVM Model: ",accuracy_score(y_test,svm_predicted_y))

Accuracy on SVM Model:  0.7261904761904762


In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy on SVM Model: ",accuracy_score(y_test,svm_predicted_y))

Accuracy on SVM Model:  0.7261904761904762


In [ ]:
knn = KNeighborsClassifier(n_neighbors=10)

In [ ]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [ ]:
knn_predicted = knn.predict(X_test)

In [ ]:
print(" KNN Classification Report: \n{}\n".format(metrics.classification_report(y_test, knn_predicted, target_names=['0','1','2'], zero_division = 1)))

 KNN Classification Report: 
              precision    recall  f1-score   support

           0       0.73      0.71      0.72        56
           1       0.70      0.90      0.79        70
           2       1.00      0.55      0.71        42

    accuracy                           0.75       168
   macro avg       0.81      0.72      0.74       168
weighted avg       0.78      0.75      0.75       168


